update_radar_zone:
  name: Update Zone
  description: Save zone data.
  fields:
    radar_name:
      description: Radar name
      example: rd_livingroom
    zone_type:
      description: include_zones or exclude_zones
      example: include_zones
    points:
      description: List of [x, y] coordinates
      example: [[10,10], [20,20]]

refresh_radar_data:
  name: Refresh Data
  description: Reload from disk.

hard_reset_radar:
  name: Hard Reset
  description: Wipe database.